package com.ui;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Objects;

public class AboutFrame extends BaseFrame {
    private JPanel aboutPanel;
    private JLabel logo;
    private JButton closeButton;
    private JLabel headLineLabel;
    private JLabel retailHubLabel;

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public AboutFrame() {
        super();
        setContentPane(aboutPanel);
        ImageIcon logoIcon = new ImageIcon(Objects.requireNonNull(getClass().getResource("/images/logo.jpeg")));
        logo.setIcon(logoIcon);
        setTitle("Krush Team");
        pack();
        Font currentFont = headLineLabel.getFont();
        headLineLabel.setFont(new Font(currentFont.getName(), currentFont.getStyle(), 24));
        retailHubLabel.setFont(new Font(currentFont.getName(), currentFont.getStyle(), 32));
        //close btn
        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        aboutPanel = new JPanel();
        aboutPanel.setLayout(new GridBagLayout());
        aboutPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(30, 30, 30, 30), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        logo = new JLabel();
        logo.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        aboutPanel.add(logo, gbc);
        closeButton = new JButton();
        closeButton.setText("Close");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        aboutPanel.add(closeButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("PM");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        aboutPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Antoinette");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        aboutPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Themis");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        aboutPanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Repairer of reputations ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        aboutPanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Chris B");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        aboutPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Money bags");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        aboutPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Chris T");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        aboutPanel.add(label7, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("DB sufferer ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        aboutPanel.add(label8, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Script Corrector");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        aboutPanel.add(label9, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Angelique");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        aboutPanel.add(label10, gbc);
        final JLabel label11 = new JLabel();
        label11.setText("Panic attack survivor");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        aboutPanel.add(label11, gbc);
        final JLabel label12 = new JLabel();
        label12.setText("Paraskevi");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        aboutPanel.add(label12, gbc);
        final JLabel label13 = new JLabel();
        label13.setText("Python appreciator");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        aboutPanel.add(label13, gbc);
        final JLabel label14 = new JLabel();
        label14.setText("Alex");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        aboutPanel.add(label14, gbc);
        retailHubLabel = new JLabel();
        retailHubLabel.setText("RetailHUB");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        aboutPanel.add(retailHubLabel, gbc);
        headLineLabel = new JLabel();
        headLineLabel.setText("Krush Team Prudly presents:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        aboutPanel.add(headLineLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return aboutPanel;
    }

}
