package com.ui;

import com.dao.UserDAO;
import com.model.User;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;

public class LoginFrame extends BaseFrame {
    private JPanel loginPanel;
    private JTextField inputUsername;
    private JPasswordField inputPassword;
    private JButton btnLogin;
    private JButton exitButton;
    private JLabel welcomeLabel;

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public LoginFrame(AppState appState) throws SQLException {
        super();

        setContentPane(loginPanel);// don't forget this, the window will be empty
        setTitle("Welcome! Please Login");
        setSize(600, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        //by making btnLogin default btn "ENTER" activates it
        getRootPane().setDefaultButton(btnLogin);

        //font changes
        Font currentFont = welcomeLabel.getFont();
        welcomeLabel.setFont(new Font(currentFont.getName(), currentFont.getStyle(), 32));

        //create a button listener
        ActionListener OnClick = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                authenticate(appState);
            }
        };
        //connect listener to the button
        btnLogin.addActionListener(OnClick);

        //exit button
        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                appState.resetState();
            }
        });

    }

    private void authenticate(AppState appState) {
        ArrayList<User> users = null;
        try {
            users = UserDAO.getData();
        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
        String userEmail = inputUsername.getText();
        String password = inputPassword.getText();
        System.out.println("Username: " + userEmail);
        System.out.println("Password: " + password);

        //auth
        boolean usermatch = false;
        for (User user : users) {
            if (user.getEmail().equals(userEmail)) {
                usermatch = true;
                if (user.getUserPassword().equals(password)) {
                    appState.loggedInUserName = user.getName();
                    appState.loggedInUserIsAdmin = user.getIsAdmin();
                    new MainFrame(appState).setVisible(true);
                    dispose();//this makes THIS frame not visible
                } else {
                    JOptionPane.showMessageDialog(loginPanel, "Wrong password!");
                    //          System.out.println("Wrong password");
                }
            }
        }
        if (!usermatch) {
            JOptionPane.showMessageDialog(loginPanel, "User doesn't match!");
            //      System.out.println("User doesn't match");
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loginPanel = new JPanel();
        loginPanel.setLayout(new GridBagLayout());
        loginPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(30, 30, 30, 30), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Username");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        loginPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        loginPanel.add(label2, gbc);
        inputPassword = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(inputPassword, gbc);
        btnLogin = new JButton();
        btnLogin.setText("Login");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(btnLogin, gbc);
        exitButton = new JButton();
        exitButton.setText("Exit");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(exitButton, gbc);
        inputUsername = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(inputUsername, gbc);
        welcomeLabel = new JLabel();
        welcomeLabel.setText("Welcome to RetailHUB");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        loginPanel.add(welcomeLabel, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Please Login to enter");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        loginPanel.add(label3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginPanel;
    }

}

